const { createClient } = require('@libsql/client');

const url = 'libsql://ogalley-pos-igcodeui.aws-ap-northeast-1.turso.io';
const token = 'eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODQ2NzE5MTYsImlkIjoiMDE5Zjg2YWYtZmIwMS03OTM2LTk5MzctYjU0YmYxMzUwZmM0Iiwia2lkIjoiWUNQNzBBdTdLWTJZaTk2NGtKdnF4c2tGVXlGa1liOHVaUWxtUUoxRlZLOCIsInJpZCI6IjY4NjQ4MzI4LTk4NmUtNGRkMi04M2FjLTUyMTcyNzIyMDkxYiJ9.CpecowLVjNtBA1TOY9-kWdJFEUpRTdIMPnxVHD7eBpdcEQlPAhsLM0LQEQLle57ZGvXIovZ3HMaHRaBDZDK1Bg';

const sql = `
DROP TABLE IF EXISTS test;
CREATE TABLE IF NOT EXISTS "Store" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "address" TEXT, "phone" TEXT, "email" TEXT, "logoUrl" TEXT, "taxRate" REAL NOT NULL DEFAULT 0.12, "currency" TEXT NOT NULL DEFAULT 'PHP', "footerMessage" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS "Category" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "description" TEXT, "icon" TEXT, "color" TEXT, "sortOrder" INTEGER NOT NULL DEFAULT 0, "isActive" BOOLEAN NOT NULL DEFAULT 1, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS "Supplier" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "contactPerson" TEXT, "phone" TEXT, "email" TEXT, "address" TEXT, "notes" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT 1, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS "Product" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "description" TEXT, "sku" TEXT NOT NULL, "barcode" TEXT, "imageUrl" TEXT, "costPrice" REAL NOT NULL DEFAULT 0, "sellingPrice" REAL NOT NULL, "isAvailable" BOOLEAN NOT NULL DEFAULT 1, "isFavorite" BOOLEAN NOT NULL DEFAULT 0, "categoryIds" TEXT NOT NULL, "variants" TEXT, "addons" TEXT, "recipe" TEXT, "sizeOptions" TEXT, "hasSugarLevel" BOOLEAN NOT NULL DEFAULT 0, "hasIceLevel" BOOLEAN NOT NULL DEFAULT 0, "hasHotCold" BOOLEAN NOT NULL DEFAULT 0, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "Product_sku_key" ON "Product"("sku");
CREATE TABLE IF NOT EXISTS "Ingredient" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "description" TEXT, "unit" TEXT NOT NULL DEFAULT 'pcs', "costPerUnit" REAL NOT NULL DEFAULT 0, "currentStock" REAL NOT NULL DEFAULT 0, "minStock" REAL NOT NULL DEFAULT 0, "supplierId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "InventoryItem" ("id" TEXT NOT NULL PRIMARY KEY, "productId" TEXT NOT NULL, "currentStock" REAL NOT NULL DEFAULT 0, "minStock" REAL NOT NULL DEFAULT 5, "maxStock" REAL, "unit" TEXT NOT NULL DEFAULT 'pcs', "costPrice" REAL NOT NULL DEFAULT 0, "batchNumber" TEXT, "expiryDate" DATETIME, "lastRestocked" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "InventoryLog" ("id" TEXT NOT NULL PRIMARY KEY, "ingredientId" TEXT, "productId" TEXT, "type" TEXT NOT NULL, "quantity" REAL NOT NULL, "previousStock" REAL NOT NULL, "newStock" REAL NOT NULL, "reason" TEXT, "performedBy" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("ingredientId") REFERENCES "Ingredient"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "WasteLog" ("id" TEXT NOT NULL PRIMARY KEY, "ingredientId" TEXT NOT NULL, "quantity" REAL NOT NULL, "reason" TEXT, "costValue" REAL NOT NULL, "performedBy" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("ingredientId") REFERENCES "Ingredient"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "PurchaseOrder" ("id" TEXT NOT NULL PRIMARY KEY, "poNumber" TEXT NOT NULL, "supplierId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "totalAmount" REAL NOT NULL DEFAULT 0, "notes" TEXT, "receivedBy" TEXT, "receivedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX IF NOT EXISTS "PurchaseOrder_poNumber_key" ON "PurchaseOrder"("poNumber");
CREATE TABLE IF NOT EXISTS "PurchaseOrderItem" ("id" TEXT NOT NULL PRIMARY KEY, "purchaseOrderId" TEXT NOT NULL, "productId" TEXT, "ingredientName" TEXT, "quantity" REAL NOT NULL, "unitPrice" REAL NOT NULL, "totalPrice" REAL NOT NULL, "receivedQty" REAL NOT NULL DEFAULT 0, FOREIGN KEY ("purchaseOrderId") REFERENCES "PurchaseOrder"("id") ON DELETE RESTRICT ON UPDATE CASCADE, FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "Customer" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "phone" TEXT, "email" TEXT, "birthday" DATETIME, "address" TEXT, "loyaltyPoints" INTEGER NOT NULL DEFAULT 0, "cashbackBalance" REAL NOT NULL DEFAULT 0, "membershipLevel" TEXT NOT NULL DEFAULT 'BRONZE', "totalSpent" REAL NOT NULL DEFAULT 0, "totalVisits" INTEGER NOT NULL DEFAULT 0, "referralCode" TEXT, "referredBy" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "Customer_referralCode_key" ON "Customer"("referralCode");
CREATE TABLE IF NOT EXISTS "Employee" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT, "role" TEXT NOT NULL DEFAULT 'CASHIER', "pin" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT 1, "hireDate" DATETIME, "hourlyRate" REAL NOT NULL DEFAULT 0, "commissionRate" REAL NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "Employee_email_key" ON "Employee"("email");
CREATE TABLE IF NOT EXISTS "Attendance" ("id" TEXT NOT NULL PRIMARY KEY, "employeeId" TEXT NOT NULL, "clockIn" DATETIME NOT NULL, "clockOut" DATETIME, "shift" TEXT NOT NULL DEFAULT 'MORNING', "hoursWorked" REAL, "overtimeHours" REAL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "CashDrawer" ("id" TEXT NOT NULL PRIMARY KEY, "employeeId" TEXT NOT NULL, "openingAmount" REAL NOT NULL, "closingAmount" REAL, "status" TEXT NOT NULL DEFAULT 'OPEN', "openedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "closedAt" DATETIME, "notes" TEXT, FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "SalesPerformance" ("id" TEXT NOT NULL PRIMARY KEY, "employeeId" TEXT NOT NULL, "date" DATETIME NOT NULL, "totalSales" REAL NOT NULL DEFAULT 0, "transactionCount" INTEGER NOT NULL DEFAULT 0, "averageOrderValue" REAL NOT NULL DEFAULT 0, "commission" REAL NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "Order" ("id" TEXT NOT NULL PRIMARY KEY, "orderNumber" TEXT NOT NULL, "customerId" TEXT, "employeeId" TEXT, "orderType" TEXT NOT NULL DEFAULT 'DINE_IN', "status" TEXT NOT NULL DEFAULT 'COMPLETED', "subtotal" REAL NOT NULL DEFAULT 0, "discountAmount" REAL NOT NULL DEFAULT 0, "discountType" TEXT, "discountCode" TEXT, "taxAmount" REAL NOT NULL DEFAULT 0, "taxExempt" BOOLEAN NOT NULL DEFAULT 0, "totalAmount" REAL NOT NULL DEFAULT 0, "amountPaid" REAL NOT NULL DEFAULT 0, "changeAmount" REAL NOT NULL DEFAULT 0, "paymentMethod" TEXT NOT NULL DEFAULT 'CASH', "paymentNote" TEXT, "referenceNumber" TEXT, "notes" TEXT, "isSplit" BOOLEAN NOT NULL DEFAULT 0, "splitFromOrderId" TEXT, "loyaltyPointsEarned" INTEGER NOT NULL DEFAULT 0, "receiptPrinted" BOOLEAN NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE UNIQUE INDEX IF NOT EXISTS "Order_orderNumber_key" ON "Order"("orderNumber");
CREATE TABLE IF NOT EXISTS "OrderItem" ("id" TEXT NOT NULL PRIMARY KEY, "orderId" TEXT NOT NULL, "productId" TEXT NOT NULL, "productName" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "unitPrice" REAL NOT NULL, "subtotal" REAL NOT NULL, "variant" TEXT, "size" TEXT, "sugarLevel" TEXT, "iceLevel" TEXT, "temperature" TEXT, "addons" TEXT, "notes" TEXT, "costPrice" REAL NOT NULL DEFAULT 0, "profit" REAL NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE, FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "Payment" ("id" TEXT NOT NULL PRIMARY KEY, "orderId" TEXT NOT NULL, "method" TEXT NOT NULL, "amount" REAL NOT NULL, "referenceNumber" TEXT, "notes" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "Refund" ("id" TEXT NOT NULL PRIMARY KEY, "orderId" TEXT NOT NULL, "reason" TEXT NOT NULL, "amount" REAL NOT NULL, "refundedBy" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "Discount" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "code" TEXT, "type" TEXT NOT NULL, "value" REAL NOT NULL, "minOrderAmount" REAL, "maxUses" INTEGER, "currentUses" INTEGER NOT NULL DEFAULT 0, "validFrom" DATETIME, "validUntil" DATETIME, "isActive" BOOLEAN NOT NULL DEFAULT 1, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "Discount_code_key" ON "Discount"("code");
CREATE TABLE IF NOT EXISTS "GiftCertificate" ("id" TEXT NOT NULL PRIMARY KEY, "code" TEXT NOT NULL, "initialAmount" REAL NOT NULL, "remainingAmount" REAL NOT NULL, "customerId" TEXT, "issuedBy" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT 1, "expiresAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS "GiftCertificate_code_key" ON "GiftCertificate"("code");
CREATE TABLE IF NOT EXISTS "Notification" ("id" TEXT NOT NULL PRIMARY KEY, "type" TEXT NOT NULL, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "isRead" BOOLEAN NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "ActivityLog" ("id" TEXT NOT NULL PRIMARY KEY, "employeeId" TEXT, "action" TEXT NOT NULL, "entity" TEXT, "entityId" TEXT, "details" TEXT, "ipAddress" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "StoreSettings" ("id" TEXT NOT NULL PRIMARY KEY, "key" TEXT NOT NULL, "value" TEXT NOT NULL, "description" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "StoreSettings_key_key" ON "StoreSettings"("key");
`;

async function main() {
  const client = createClient({ url, authToken: token });
  const statements = sql.split(';').filter(s => s.trim());
  for (const stmt of statements) {
    try {
      await client.execute(stmt.trim());
      console.log('OK');
    } catch (e) {
      console.error('ERROR:', e.message);
    }
  }
  const result = await client.execute('SELECT name FROM sqlite_master WHERE type="table" ORDER BY name');
  console.log('\nTables created:', result.rows.length);
  result.rows.forEach(r => console.log(' -', r.name));
}

main();